#.travis.yml

language: node_js
node_js:
  - "9.4"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install --save @angular/material @angular/cdk
  - npm install SteveDunlap13/MaterialTimeControl

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change